config/routes.rb
Rails.application.routes.draw do
  resources :presidencies
  root "cabinets#index"
  resources :comments
  devise_for :users, :controllers => {:registrations => "users/registrations"}
  resources :cabinets
  resources :questions
  resources :answers
  
  devise_scope :user do
    post 'users/secretary' => 'users/registrations#secretary', as: :create_secretary
  end
  

end

app/models/presidency.rb
class Presidency < ActiveRecord::Base
  belongs_to :cabinet
end

app/controllers/presidencies_controller.rb
class PresidenciesController < ApplicationController
  before_action :set_presidency, only: [:show, :edit, :update, :destroy]

  # GET /presidencies
  # GET /presidencies.json
  def index
    @presidencies = Presidency.all
  end

  # GET /presidencies/1
  # GET /presidencies/1.json
  def show
  end

  # GET /presidencies/new
  def new
    @presidency = Presidency.new
  end

  # GET /presidencies/1/edit
  def edit
  end

  # POST /presidencies
  # POST /presidencies.json
  def create
    @presidency = Presidency.new(presidency_params)

    respond_to do |format|
      if @presidency.save
        format.html { redirect_to @presidency, notice: 'Presidency was successfully created.' }
        format.json { render :show, status: :created, location: @presidency }
      else
        format.html { render :new }
        format.json { render json: @presidency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presidencies/1
  # PATCH/PUT /presidencies/1.json
  def update
    respond_to do |format|
      if @presidency.update(presidency_params)
        format.html { redirect_to @presidency, notice: 'Presidency was successfully updated.' }
        format.json { render :show, status: :ok, location: @presidency }
      else
        format.html { render :edit }
        format.json { render json: @presidency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presidencies/1
  # DELETE /presidencies/1.json
  def destroy
    @presidency.destroy
    respond_to do |format|
      format.html { redirect_to presidencies_url, notice: 'Presidency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presidency
      @presidency = Presidency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presidency_params
      params.require(:presidency).permit(:cabinet_id)
    end
end

app/helpers/presidencies_helper.rb
module PresidenciesHelper
end

app/views/presidencies/_form.html.erb
<%= form_for(@presidency) do |f| %>
  <% if @presidency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@presidency.errors.count, "error") %> prohibited this presidency from being saved:</h2>

      <ul>
      <% @presidency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cabinet_id %><br>
    <%= f.number_field :cabinet_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presidencies/edit.html.erb
<h1>Editing Presidency</h1>

<%= render 'form' %>

<%= link_to 'Show', @presidency %> |
<%= link_to 'Back', presidencies_path %>

app/views/presidencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Presidencies</h1>

<table>
  <thead>
    <tr>
      <th>Cabinet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presidencies.each do |presidency| %>
      <tr>
        <td><%= presidency.cabinet_id %></td>
        <td><%= link_to 'Show', presidency %></td>
        <td><%= link_to 'Edit', edit_presidency_path(presidency) %></td>
        <td><%= link_to 'Destroy', presidency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presidency', new_presidency_path %>

app/views/presidencies/new.html.erb
<h1>New Presidency</h1>

<%= render 'form' %>

<%= link_to 'Back', presidencies_path %>

app/views/presidencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cabinet:</strong>
  <%= @presidency.cabinet_id %>
</p>

<%= link_to 'Edit', edit_presidency_path(@presidency) %> |
<%= link_to 'Back', presidencies_path %>